import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSettings } from '../../src/context/SettingsContext';

export default function TermsScreen() {
  const router = useRouter();
  const { t, language } = useSettings();

  const isRomanian = language.code === 'ro';

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color="#9d174d" />
        </TouchableOpacity>
        <Text style={styles.title}>
          {isRomanian ? 'Termeni și Condiții' : 'Terms and Conditions'}
        </Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.lastUpdated}>
          {isRomanian ? 'Ultima actualizare: Iunie 2026' : 'Last updated: June 2026'}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '1. Proprietate și Drepturi de Autor' : '1. Ownership and Copyright'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'Aplicația MomManager 2026 este proprietatea exclusivă a Dianei-Elena Albu, operând ca Sole Trader în Regatul Unit. Toate drepturile asupra codului sursă, designului, conținutului și funcționalităților aplicației sunt rezervate proprietarului.'
              : 'MomManager 2026 application is the exclusive property of Diana-Elena Albu, operating as a Sole Trader in the United Kingdom. All rights to the source code, design, content, and functionality of the application are reserved to the owner.'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '2. Scopul Aplicației' : '2. Purpose of the Application'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'MomManager 2026 este un instrument digital de organizare și planificare destinat mamelor care lucrează. Aplicația oferă funcționalități pentru gestionarea calendarului, bugetului familial, planificării meselor, urmăririi activităților copiilor și rutinelor de îngrijire personală.'
              : 'MomManager 2026 is a digital organization and planning tool designed for working mothers. The application provides features for managing calendars, family budgets, meal planning, tracking children\'s activities, and personal care routines.'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '3. Excluderea Responsabilității' : '3. Disclaimer'}
          </Text>
          <View style={styles.warningBox}>
            <Ionicons name="warning" size={24} color="#f59e0b" />
            <Text style={styles.warningText}>
              {isRomanian
                ? 'IMPORTANT: Această aplicație NU oferă consultanță medicală, nutrițională sau financiară oficială.'
                : 'IMPORTANT: This application does NOT provide official medical, nutritional, or financial advice.'}
            </Text>
          </View>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'Informațiile și sugestiile furnizate de MomManager 2026, inclusiv cele generate de sistemul AI, sunt oferite exclusiv în scop informativ și de organizare personală. Acestea nu înlocuiesc:\n\n• Consultația unui medic sau specialist în sănătate\n• Sfaturile unui nutriționist sau dietetician certificat\n• Consultanța unui consilier financiar autorizat\n• Orice altă formă de consultanță profesională\n\nUtilizatorii sunt încurajați să consulte profesioniști calificați pentru decizii legate de sănătate, alimentație sau finanțe.'
              : 'The information and suggestions provided by MomManager 2026, including those generated by the AI system, are provided solely for informational and personal organization purposes. They do not replace:\n\n• Consultation with a doctor or health specialist\n• Advice from a certified nutritionist or dietitian\n• Guidance from an authorized financial advisor\n• Any other form of professional consultation\n\nUsers are encouraged to consult qualified professionals for decisions related to health, nutrition, or finances.'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '4. Utilizarea Serviciului' : '4. Use of Service'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'Prin utilizarea aplicației MomManager 2026, acceptați să:\n\n• Furnizați informații corecte la înregistrare\n• Nu utilizați aplicația în scopuri ilegale\n• Nu încercați să accesați neautorizat sistemele noastre\n• Respectați drepturile de proprietate intelectuală\n• Nu redistribuiți sau copiați conținutul aplicației'
              : 'By using the MomManager 2026 application, you agree to:\n\n• Provide accurate information during registration\n• Not use the application for illegal purposes\n• Not attempt unauthorized access to our systems\n• Respect intellectual property rights\n• Not redistribute or copy the application content'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '5. Abonamente și Plăți' : '5. Subscriptions and Payments'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'MomManager 2026 oferă planuri de abonament lunar și anual. Toate plățile sunt procesate securizat prin Stripe. Puteți anula abonamentul în orice moment din setările aplicației. Rambursările sunt gestionate conform politicii platformei de plăți.'
              : 'MomManager 2026 offers monthly and annual subscription plans. All payments are securely processed through Stripe. You can cancel your subscription at any time from the app settings. Refunds are handled according to the payment platform\'s policy.'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '6. Modificări ale Termenilor' : '6. Changes to Terms'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'Ne rezervăm dreptul de a modifica acești termeni în orice moment. Utilizatorii vor fi notificați prin aplicație despre orice modificări semnificative. Continuarea utilizării aplicației după modificări constituie acceptarea noilor termeni.'
              : 'We reserve the right to modify these terms at any time. Users will be notified through the app about any significant changes. Continued use of the application after modifications constitutes acceptance of the new terms.'}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {isRomanian ? '7. Contact' : '7. Contact'}
          </Text>
          <Text style={styles.sectionText}>
            {isRomanian
              ? 'Pentru întrebări despre acești termeni, vă rugăm să ne contactați:\n\nDiana-Elena Albu\nProprietar MomManager 2026\nEmail: dianaalbu661@yahoo.com'
              : 'For questions about these terms, please contact us:\n\nDiana-Elena Albu\nOwner of MomManager 2026\nEmail: dianaalbu661@yahoo.com'}
          </Text>
        </View>

        {/* Copyright Footer */}
        <View style={styles.copyrightContainer}>
          <Text style={styles.copyrightText}>
            © 2026 MomManager by Diana-Elena Albu. All rights reserved. Unauthorized reproduction or distribution of this app's content, code, or design is strictly prohibited.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fdf2f8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#fce7f3',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fce7f3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#9d174d',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  lastUpdated: {
    fontSize: 13,
    color: '#9ca3af',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#9d174d',
    marginBottom: 12,
  },
  sectionText: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 22,
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fef3c7',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 10,
  },
  warningText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#92400e',
    lineHeight: 20,
  },
  copyrightContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#fce7f3',
    marginBottom: 40,
  },
  copyrightText: {
    fontSize: 11,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 16,
  },
});
